apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Redis
      type: redis-datasource
      isDefault: true
      jsonData:
        poolSize: 5
        timeout: 10
        pingInterval: 0
        pipelineWindow: 0
      secureJsonData:
        password: ""
      url: valkey.sopes3.svc.cluster.local:6379
      uid: redis
      editable: true