apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-kafka-writer
  namespace: sopes3
  labels:
    app: go-kafka-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-kafka-writer
  template:
    metadata:
      labels:
        app: go-kafka-writer
    spec:
      containers:
      - name: go-kafka-writer
        image: 35.188.198.252:5000/go-kafka-writer:latest
        ports:
        - containerPort: 50051
        env:
        - name: GRPC_PORT
          value: "50051"
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "weather-tweets"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-kafka-writer-service
  namespace: sopes3
spec:
  selector:
    app: go-kafka-writer
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: ClusterIP
