apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rabbitmq-writer
  namespace: sopes3
  labels:
    app: go-rabbitmq-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-rabbitmq-writer
  template:
    metadata:
      labels:
        app: go-rabbitmq-writer
    spec:
      containers:
      - name: go-rabbitmq-writer
        image: 35.188.198.252:5000/go-rabbitmq-writer:latest
        ports:
        - containerPort: 50052
        env:
        - name: GRPC_PORT
          value: "50052"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        - name: RABBITMQ_QUEUE
          value: "weather-tweets"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-rabbitmq-writer-service
  namespace: sopes3
spec:
  selector:
    app: go-rabbitmq-writer
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052
  type: ClusterIP
