apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: sopes3
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: 35.188.198.252:5000/kafka-consumer:latest
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "weather-tweets"
        - name: KAFKA_GROUP_ID
          value: "kafka-consumer-group"
        - name: VALKEY_ADDR
          value: "valkey-service:6379"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
