apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: sopes3
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: valkey
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: sopes3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --save
        - "60 1"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: valkey-data
          mountPath: /data
      volumes:
      - name: valkey-data
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
  namespace: sopes3
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    save 60 1
