// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/weathertweet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lista de los únicos posibles municipios aceptados por el proyecto
type Municipalities int32

const (
	Municipalities_municipalities_unknown Municipalities = 0
	Municipalities_mixco                  Municipalities = 1
	Municipalities_guatemala              Municipalities = 2
	Municipalities_amatitlan              Municipalities = 3
	Municipalities_chinautla              Municipalities = 4
)

// Enum value maps for Municipalities.
var (
	Municipalities_name = map[int32]string{
		0: "municipalities_unknown",
		1: "mixco",
		2: "guatemala",
		3: "amatitlan",
		4: "chinautla",
	}
	Municipalities_value = map[string]int32{
		"municipalities_unknown": 0,
		"mixco":                  1,
		"guatemala":              2,
		"amatitlan":              3,
		"chinautla":              4,
	}
)

func (x Municipalities) Enum() *Municipalities {
	p := new(Municipalities)
	*p = x
	return p
}

func (x Municipalities) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Municipalities) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_weathertweet_proto_enumTypes[0].Descriptor()
}

func (Municipalities) Type() protoreflect.EnumType {
	return &file_proto_weathertweet_proto_enumTypes[0]
}

func (x Municipalities) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Municipalities.Descriptor instead.
func (Municipalities) EnumDescriptor() ([]byte, []int) {
	return file_proto_weathertweet_proto_rawDescGZIP(), []int{0}
}

// Lista de los únicos posibles climas aceptados por el proyecto
type Weathers int32

const (
	Weathers_weathers_unknown Weathers = 0
	Weathers_sunny            Weathers = 1
	Weathers_cloudy           Weathers = 2
	Weathers_rainy            Weathers = 3
	Weathers_foggy            Weathers = 4
)

// Enum value maps for Weathers.
var (
	Weathers_name = map[int32]string{
		0: "weathers_unknown",
		1: "sunny",
		2: "cloudy",
		3: "rainy",
		4: "foggy",
	}
	Weathers_value = map[string]int32{
		"weathers_unknown": 0,
		"sunny":            1,
		"cloudy":           2,
		"rainy":            3,
		"foggy":            4,
	}
)

func (x Weathers) Enum() *Weathers {
	p := new(Weathers)
	*p = x
	return p
}

func (x Weathers) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Weathers) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_weathertweet_proto_enumTypes[1].Descriptor()
}

func (Weathers) Type() protoreflect.EnumType {
	return &file_proto_weathertweet_proto_enumTypes[1]
}

func (x Weathers) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Weathers.Descriptor instead.
func (Weathers) EnumDescriptor() ([]byte, []int) {
	return file_proto_weathertweet_proto_rawDescGZIP(), []int{1}
}

// Mensaje que se enviará
type WeatherTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Municipality Municipalities `protobuf:"varint,1,opt,name=municipality,proto3,enum=weathertweet.Municipalities" json:"municipality,omitempty"`
	Temperature  int32          `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity     int32          `protobuf:"varint,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Weather      Weathers       `protobuf:"varint,4,opt,name=weather,proto3,enum=weathertweet.Weathers" json:"weather,omitempty"`
}

func (x *WeatherTweetRequest) Reset() {
	*x = WeatherTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weathertweet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherTweetRequest) ProtoMessage() {}

func (x *WeatherTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weathertweet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherTweetRequest.ProtoReflect.Descriptor instead.
func (*WeatherTweetRequest) Descriptor() ([]byte, []int) {
	return file_proto_weathertweet_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherTweetRequest) GetMunicipality() Municipalities {
	if x != nil {
		return x.Municipality
	}
	return Municipalities_municipalities_unknown
}

func (x *WeatherTweetRequest) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherTweetRequest) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherTweetRequest) GetWeather() Weathers {
	if x != nil {
		return x.Weather
	}
	return Weathers_weathers_unknown
}

// Respuesta del servidor
type WeatherTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *WeatherTweetResponse) Reset() {
	*x = WeatherTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weathertweet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherTweetResponse) ProtoMessage() {}

func (x *WeatherTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weathertweet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherTweetResponse.ProtoReflect.Descriptor instead.
func (*WeatherTweetResponse) Descriptor() ([]byte, []int) {
	return file_proto_weathertweet_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherTweetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_weathertweet_proto protoreflect.FileDescriptor

var file_proto_weathertweet_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x74, 0x77, 0x65, 0x65, 0x74, 0x22, 0xc7, 0x01, 0x0a, 0x13, 0x57, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x40, 0x0a, 0x0c, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x4d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x52, 0x0c, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x12, 0x30, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x73, 0x52, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x22, 0x2e, 0x0a, 0x14, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x54, 0x77, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2a, 0x64, 0x0a, 0x0e, 0x4d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x16, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x6d, 0x69, 0x78, 0x63, 0x6f, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x67,
	0x75, 0x61, 0x74, 0x65, 0x6d, 0x61, 0x6c, 0x61, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x61, 0x6d,
	0x61, 0x74, 0x69, 0x74, 0x6c, 0x61, 0x6e, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x68, 0x69,
	0x6e, 0x61, 0x75, 0x74, 0x6c, 0x61, 0x10, 0x04, 0x2a, 0x4d, 0x0a, 0x08, 0x57, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x73,
	0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x73, 0x75,
	0x6e, 0x6e, 0x79, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x79, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x61, 0x69, 0x6e, 0x79, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x66, 0x6f, 0x67, 0x67, 0x79, 0x10, 0x04, 0x32, 0x69, 0x0a, 0x13, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x54, 0x77, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52,
	0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x77, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_weathertweet_proto_rawDescOnce sync.Once
	file_proto_weathertweet_proto_rawDescData = file_proto_weathertweet_proto_rawDesc
)

func file_proto_weathertweet_proto_rawDescGZIP() []byte {
	file_proto_weathertweet_proto_rawDescOnce.Do(func() {
		file_proto_weathertweet_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_weathertweet_proto_rawDescData)
	})
	return file_proto_weathertweet_proto_rawDescData
}

var file_proto_weathertweet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_weathertweet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_weathertweet_proto_goTypes = []interface{}{
	(Municipalities)(0),          // 0: weathertweet.Municipalities
	(Weathers)(0),                // 1: weathertweet.Weathers
	(*WeatherTweetRequest)(nil),  // 2: weathertweet.WeatherTweetRequest
	(*WeatherTweetResponse)(nil), // 3: weathertweet.WeatherTweetResponse
}
var file_proto_weathertweet_proto_depIdxs = []int32{
	0, // 0: weathertweet.WeatherTweetRequest.municipality:type_name -> weathertweet.Municipalities
	1, // 1: weathertweet.WeatherTweetRequest.weather:type_name -> weathertweet.Weathers
	2, // 2: weathertweet.WeatherTweetService.SendTweet:input_type -> weathertweet.WeatherTweetRequest
	3, // 3: weathertweet.WeatherTweetService.SendTweet:output_type -> weathertweet.WeatherTweetResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_weathertweet_proto_init() }
func file_proto_weathertweet_proto_init() {
	if File_proto_weathertweet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_weathertweet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeatherTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weathertweet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeatherTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_weathertweet_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_weathertweet_proto_goTypes,
		DependencyIndexes: file_proto_weathertweet_proto_depIdxs,
		EnumInfos:         file_proto_weathertweet_proto_enumTypes,
		MessageInfos:      file_proto_weathertweet_proto_msgTypes,
	}.Build()
	File_proto_weathertweet_proto = out.File
	file_proto_weathertweet_proto_rawDesc = nil
	file_proto_weathertweet_proto_goTypes = nil
	file_proto_weathertweet_proto_depIdxs = nil
}
